### ISSUE TITLE
(features)I want to visit the home page with all tricks

### ISSUE THREAD

**Issue by romainromss** [romainromss/snowtricks#1]
*Created by: romainromss*

## Specification
the tricks are displayed on this page and are paginated by 10 If a user is logged in, a modified button will be displayed, and a delete button will appear.

## Task
- [x] Create the route
- [x] Create a method __invoke using the Tricks repository and a getAll () method.
- [x] Pass parameters Request, TricksRepository, Response
- [x] Return a new response with Twig render

## Routing
The route is named index

## Test
- [x] I want my page to be accessible
- [x] I want all the tricks to show up.

**Comment by romainromss** [comment]
WIP /test and button delete, update
