### ISSUE TITLE
(features)I want update a Tricks

### ISSUE THREAD

**Issue by romainromss** [romainromss/snowtricks#11]
*Created by: romainromss*

## Specifications
I want to update a trick with a new image, video, change the name, description etc ...

## Task	  
- [x] Create the route
- [x] Create a method __invoke using the Tricks repository and a getBySlug ().
- [x] Pass parametersRequest,TricksRepositoryInterface, Response
- [x] Return a new response with Twig render

## Routing  
The route is named tricks_update

## Test  
- [x] I want update a trick
