### ISSUE TITLE
(features)I want to see only one trick in detail

### ISSUE THREAD

**Issue by romainromss** [romainromss/snowtricks#2]
*Created by: romainromss*

## Specifications
All his information must be in there: name of tricks; his description; the tricks group; the photo (s) attached to the tricks; the video (s) attached to the tricks; discussion space

## Task	  
- [x] Create the route
- [x] Create a method __invoke using the Tricks repository and a getById ().
- [x] Pass parametersRequest,TricksRepositoryInterface,CommentRepositoryInterface Response
- [x] Return a new response with Twig render

## Routing  
The route is named tricks_details

## Test  
[ ] I want read a trick

**Comment by romainromss** [comment]
Don't forget token storage
