### ISSUE TITLE
(features) I want add a comment

### ISSUE THREAD

**Issue by romainromss** [romainromss/snowtricks#3]
*Created by: romainromss*

## Specifications
Users who are not authenticated can view the threads of all tricks. However, they cannot post a message.

For each message, the following information will be displayed:
the full name of the author of the message;
the photo of the author of the message;
the date the message was created;
the content of the message.

In this discussion area, you can see the list of messages posted by members, from the most recent to the oldest.
These messages must be paginated (10 per page).

If the user is authenticated, he can see a form above the list with a mandatory "message" field. The user can post as many messages as he wants.

## Task
- [x] Create the route
- [x] Create __construct
- [x] Create a method __invoke 
- [x] Pass parameters
- [x] Return a new response with Twig render

##Routing
 No routes for this action only POST action

## Test
- [x] I want post a comment
- [x] Verify authentication

**Comment by romainromss** [comment]
don't forget token storage
