### ISSUE TITLE
(features) I want Add Tricks

### ISSUE THREAD

**Issue by romainromss** [romainromss/snowtricks#4]
*Created by: romainromss*

## Specification
The form will contain the following fields:
name;
description
group of the figure;
one or more illustrations;
one or more videos.

The form is only accessible if the user is authenticated.

When the user submits the form, it is necessary that:
this figure does not already exist in the database (unicity constraint on the name);
it is redirected to the page listing figures with a flash message giving an indication of the good progress of the database recording or an error that has occurred.

For videos, the user will be able to paste an embed tag from the platform of his choice (Youtube, Dailymotion...).

## Task
- [x] Create the route
- [x] Create __construct
- [x] Create __invoke
- [x] Return a new Response 
- [x] Create Form
- [x] Create Pagination

## Routing
The Route is named add_tricks

## Test
- [x] I want than the form is ok
