### ISSUE TITLE
(features)User Login

### ISSUE THREAD

**Issue by romainromss** [romainromss/snowtricks#5]
*Created by: romainromss*

## Specification
The form will contain the following fields:
username;
password;

The form is only accessible if the user is not authenticated.

When the user submits the form, it is necessary that:
this name does not already exist in the database (unicity constraint on the name);
it is redirected to the home page with a flash message giving an indication of the good progress of the database recording or an error that has occurred.

## Task
- [x] Create the route
- [x] Create __construct
- [x] Create __invoke
- [x] Return a new Response 
- [x] Create Form

## Routing
The Route is named tricks_login

## Test
- [x] I want than the form is ok
