### ISSUE TITLE
(features) Register User

### ISSUE THREAD

**Issue by romainromss** [romainromss/snowtricks#6]
*Created by: romainromss*

## Specification
The form will contain the following fields:
name;
username;
lastname;
mail;
password;
profile_picture;

The form is only accessible if the user is anonymous.

When the user submits the form, it is necessary that:
this username and mail does not already exist in the database (unicity constraint on the username and mail);

it is redirected to the home page with a flash message giving an indication of the good progress of the database recording or an error that has occurred.

## Task
- [x] Create the route
- [x] Create __construct
- [x] Create __invoke
- [x] Return a new Response 
- [x] Create Form

## Routing
The Route is named register_user

## Test
- [x] I want than the form is ok
