### ISSUE TITLE
(features)Reset password

### ISSUE THREAD

**Issue by romainromss** [romainromss/snowtricks#7]
*Created by: romainromss*

## Specification
The form will contain the following fields:
username;
mail;

The form is only accessible if the user is anonymous.

When the user submits the form, it is necessary that:
verify that the user exists in the database, and then send a token email
it is redirected to the page listing figures with a flash message giving an indication of the good progress of the database recording or an error that has occurred.

## Task
- [x] Create the route
- [x] Create __construct
- [x] Create __invoke
- [x] Return a new Response 
- [x] Create Form

## Routing
The Route is named reset_password

## Test
- [x] I want than the form is ok
